[2025-03-10 00:51:50 -0700] [3240723] [INFO] Starting gunicorn 23.0.0
[2025-03-10 00:51:50 -0700] [3240723] [ERROR] Connection in use: ('0.0.0.0', 65216)
[2025-03-10 00:51:50 -0700] [3240723] [ERROR] connection to ('0.0.0.0', 65216) failed: [Errno 98] Address already in use
[2025-03-10 00:51:51 -0700] [3240723] [ERROR] Connection in use: ('0.0.0.0', 65216)
[2025-03-10 00:51:51 -0700] [3240723] [ERROR] connection to ('0.0.0.0', 65216) failed: [Errno 98] Address already in use
[2025-03-10 00:51:52 -0700] [3240723] [ERROR] Connection in use: ('0.0.0.0', 65216)
[2025-03-10 00:51:52 -0700] [3240723] [ERROR] connection to ('0.0.0.0', 65216) failed: [Errno 98] Address already in use
[2025-03-10 00:51:53 -0700] [3240723] [ERROR] Connection in use: ('0.0.0.0', 65216)
[2025-03-10 00:51:53 -0700] [3240723] [ERROR] connection to ('0.0.0.0', 65216) failed: [Errno 98] Address already in use
[2025-03-10 00:51:54 -0700] [3240723] [ERROR] Connection in use: ('0.0.0.0', 65216)
[2025-03-10 00:51:54 -0700] [3240723] [ERROR] connection to ('0.0.0.0', 65216) failed: [Errno 98] Address already in use
[2025-03-10 00:51:55 -0700] [3240723] [ERROR] Can't connect to ('0.0.0.0', 65216)
[2025-03-11 00:47:03 -0700] [1953646] [INFO] Starting gunicorn 23.0.0
[2025-03-11 00:47:03 -0700] [1953646] [INFO] Listening at: http://0.0.0.0:65216 (1953646)
[2025-03-11 00:47:03 -0700] [1953646] [INFO] Using worker: sync
[2025-03-11 00:47:03 -0700] [1953648] [INFO] Booting worker with pid: 1953648
[2025-03-11 00:47:03 -0700] [1953648] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2025-03-11 00:47:03 -0700] [1953648] [INFO] Worker exiting (pid: 1953648)
[2025-03-11 00:47:03 -0700] [1953646] [ERROR] Worker (pid:1953648) exited with code 3
[2025-03-11 00:47:03 -0700] [1953646] [ERROR] Shutting down: Master
[2025-03-11 00:47:03 -0700] [1953646] [ERROR] Reason: Worker failed to boot.
[2025-03-11 00:49:03 -0700] [1954203] [INFO] Starting gunicorn 23.0.0
[2025-03-11 00:49:03 -0700] [1954203] [INFO] Listening at: http://0.0.0.0:65216 (1954203)
[2025-03-11 00:49:03 -0700] [1954203] [INFO] Using worker: sync
[2025-03-11 00:49:03 -0700] [1954205] [INFO] Booting worker with pid: 1954205
[2025-03-11 00:49:03 -0700] [1954205] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2025-03-11 00:49:03 -0700] [1954205] [INFO] Worker exiting (pid: 1954205)
[2025-03-11 00:49:03 -0700] [1954203] [ERROR] Worker (pid:1954205) exited with code 3
[2025-03-11 00:49:03 -0700] [1954203] [ERROR] Shutting down: Master
[2025-03-11 00:49:03 -0700] [1954203] [ERROR] Reason: Worker failed to boot.
[2025-03-11 00:50:14 -0700] [1954594] [INFO] Starting gunicorn 23.0.0
[2025-03-11 00:50:14 -0700] [1954594] [INFO] Listening at: http://0.0.0.0:65216 (1954594)
[2025-03-11 00:50:14 -0700] [1954594] [INFO] Using worker: sync
[2025-03-11 00:50:14 -0700] [1954597] [INFO] Booting worker with pid: 1954597
[2025-03-11 00:50:14 -0700] [1954597] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2025-03-11 00:50:14 -0700] [1954597] [INFO] Worker exiting (pid: 1954597)
[2025-03-11 00:50:14 -0700] [1954594] [ERROR] Worker (pid:1954597) exited with code 3
[2025-03-11 00:50:14 -0700] [1954594] [ERROR] Shutting down: Master
[2025-03-11 00:50:14 -0700] [1954594] [ERROR] Reason: Worker failed to boot.
[2025-03-11 00:50:59 -0700] [1954792] [INFO] Starting gunicorn 23.0.0
[2025-03-11 00:50:59 -0700] [1954792] [INFO] Listening at: http://0.0.0.0:65216 (1954792)
[2025-03-11 00:50:59 -0700] [1954792] [INFO] Using worker: sync
[2025-03-11 00:50:59 -0700] [1954794] [INFO] Booting worker with pid: 1954794
[2025-03-11 00:50:59 -0700] [1954794] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/nfs/stak/users/kimh22/public_html/cs340_group39/NutriSphere_admin_panel/venv/lib64/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2025-03-11 00:50:59 -0700] [1954794] [INFO] Worker exiting (pid: 1954794)
[2025-03-11 00:50:59 -0700] [1954792] [ERROR] Worker (pid:1954794) exited with code 3
[2025-03-11 00:50:59 -0700] [1954792] [ERROR] Shutting down: Master
[2025-03-11 00:50:59 -0700] [1954792] [ERROR] Reason: Worker failed to boot.
